image: python:3.10-alpine

test:
  stage: test
  script:
  - apk add doxygen
  - pip install -U breathe sphinx sphinx_needs sphinx_rtd_theme sphinxcontrib.plantuml
  - doxygen Doxyfile
  - sphinx-build -b html doc public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - apk add doxygen
  - pip install -U breathe sphinx sphinx_needs sphinx_rtd_theme sphinxcontrib.plantuml
  - doxygen Doxyfile
  - sphinx-build -b html doc public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

